### ISSUE TITLE
functions within es6 classes are skipped

### ISSUE THREAD

**Issue by jgeorge-gc** [jared-stilwell/complexity-report#9]
See attached complexity report and test inputs. It looks like complexity report (and likely the underlying escomplex) doesn't see code within ES6 classes.  The sample (es6classtest3.js) has a class containing one function, and that doesn't show up in the complexity report (cr.txt).  A control sample without a class (es6classtest2.js) is analyzed correctly.

I tested with complexity-report 2.0.0-alpha.

**Comment by jared-stilwell** [comment]
You're entirely correct.

There are essentially two limiting factors here. The first is Esprima's support for parsing ES6 into an AST that complies with the ESTree spec. While Esprima has already implemented support for parsing ES6 classes, the escomplex module does not yet have support for processing the resulting AST nodes.

In short, once support for ES6 classes makes it into escomplex, then your classes should show up in the complexity report. Please open an issue on the [escomplex](https://github.com/jared-stilwell/escomplex/) project to support ES6 classes and I'll prioritize this accordingly.

**Comment by jgeorge-gc** [comment]
Thanks - I moved this to [escomplex](https://github.com/jared-stilwell/escomplex/issues/22).
